resources:
  repositories:
  - repository: Celestia
    type: github
    endpoint: GithubAuth
    name: levinli303/Celestia
  - repository: CelestiaCore
    type: github
    endpoint: GithubAuth
    name: levinli303/CelestiaCore
  - repository: CelestiaContent
    type: github
    endpoint: GithubAuth
    name: CelestiaProject/CelestiaContent
  - repository: CelestiaLocalization
    type: github
    endpoint: GithubAuth
    name: levinli303/CelestiaLocalization

trigger:
  branches:
    include:
    - releases/*
    - main
    - develop

stages:
- stage: Build_iOS
  displayName: 'Build iOS'
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: iphoneos
      signing: appStore
      backend: openGL

- stage: Build_Catalyst_DeveloperID_MetalANGLE
  displayName: 'Build Catalyst (Developer ID, MetalANGLE)'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: macosx
      signing: developerID
      backend: metalAngle

- stage: Build_Catalyst_DeveloperID_OpenGL
  displayName: 'Build Catalyst (Developer ID, OpenGL)'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: macosx
      signing: developerID
      backend: openGL

- stage: Build_Catalyst_App_Store
  displayName: 'Build Catalyst (App Store)'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: macosx
      signing: appStore
      backend: openGL
