resources:
  repositories:
  - repository: Celestia
    type: github
    endpoint: GithubAuth
    name: levinli303/Celestia
  - repository: CelestiaCore
    type: github
    endpoint: GithubAuth
    name: levinli303/CelestiaCore

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- checkout: Celestia
- checkout: CelestiaCore
  submodules: true
- checkout: self

- task: CmdLine@2
  inputs:
    script: |
      ln -sf libs/dependency/ios CelestiaCore/thirdparty
      brew install gettext

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'app-release.p12'
    certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'mobile_celestia.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'archive'
    packageApp: true
    signingOption: manual
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    scheme: 'MobileCelestia'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'MobileCelestia/MobileCelestia.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath


- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'MobileCelestiaAppCenter'
    appSlug: 'CelestiaProject/Celestia'
    appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
    symbolsDsymFiles: '''$(build.artifactstagingdirectory)/**/*.dsym'''
    releaseNotesOption: 'input'
    releaseNotesInput: 'release notes'
    destinationType: 'store'
    destinationStoreId: 'destination'