resources:
  repositories:
  - repository: Celestia
    type: github
    endpoint: GithubAuth
    name: levinli303/Celestia
  - repository: CelestiaCore
    type: github
    endpoint: GithubAuth
    name: levinli303/CelestiaCore

trigger:
  branches:
    include: 
    - releases/*
    - master

stages:
- stage: Build_iOS
  displayName: 'Build iOS'
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: iphoneos
      signing: appStore

- stage: Build_Catalyst_DeveloperID
  displayName: 'Build Catalyst (Developer ID)'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: macosx
      signing: developerID

- stage: Build_Catalyst_App_Store
  displayName: 'Build Catalyst (App Store)'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      sdk: macosx
      signing: appStore
