resources:
  repositories:
  - repository: Celestia
    type: github
    ref: $(System.PullRequest.TargetBranch)
    endpoint: GithubAuth
    name: levinli303/Celestia
  - repository: CelestiaCore
    type: github
    ref: $(System.PullRequest.TargetBranch)
    endpoint: GithubAuth
    name: levinli303/CelestiaCore

trigger:
  branches:
    include: 
    - releases/*
    - master

stages:
- stage: Build_iOS
  displayName: 'Build iOS'
  jobs:
  - template: jobs/build.yml
    parameters:
      useAngle: false
      sdk: iphoneos
      useMobileProvision: true
      destinationPlatform: iOS
      appCenterEndPoint: MobileCelestiaAppCenter
      appCenterAppSlug: 'CelestiaProject/Celestia'
      appExtension: ipa
- stage: Build_ARM64
  displayName: 'Build Catalyst'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      useAngle: true
      sdk: macosx
      useMobileProvision: false
      destinationPlatform: macOS
      appCenterEndPoint: MobileCelestiaAppCenter
      appCenterAppSlug: 'CelestiaProject/Celestia-3'
      appExtension: pkg
