resources:
  repositories:
  - repository: Celestia
    type: github
    name: Celestia
  - repository: CelestiaCore
    type: github
    name: CelestiaCore

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- checkout: Celestia
- checkout: CelestiaCore
- checkout: self

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'app-release.p12'
    certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'mobile_celestia.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'MobileCelestia'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'MobileCelestia.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
