#!/bin/sh

CELESTIA_IOS_ROOT=$SRCROOT/MobileCelestia/Resources
CELESTIA_LOCALIZATION_REPO_ROOT=$SRCROOT/../CelestiaLocalization
CELESTIA_LOCALIZATION_IOS_ROOT=$CELESTIA_LOCALIZATION_REPO_ROOT/ios

rsync -rv --quiet $CELESTIA_LOCALIZATION_IOS_ROOT/* $CELESTIA_IOS_ROOT
