jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'macos-11'

  variables:
    sdk: ${{ parameters.sdk }}
    signing: ${{ parameters.signing }}

  steps:
  - checkout: Celestia
  - checkout: CelestiaCore
  - checkout: self

  - script: |
      cd Celestia
      git checkout origin/$(Build.SourceBranchName)
      git submodule update --init
      cd ../CelestiaCore
      git checkout origin/$(Build.SourceBranchName)
      git submodule update --init
    displayName: 'Checkout Branch'
    condition: ne( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd Celestia
      git checkout origin/$(System.PullRequest.TargetBranch)
      git submodule update --init
      cd ../CelestiaCore
      git checkout origin/$(System.PullRequest.TargetBranch)
      git submodule update --init
    displayName: 'Checkout Branch (PR)'
    condition: eq( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd Celestia
      git cherry-pick origin/angle
    displayName: 'Cherry-Pick ANGLE Commit'
    condition: eq( variables['sdk'], 'macosx' )

  - script: |
      cd MobileCelestia
      pod deintegrate
      pod install
    displayName: 'Reintegrate CocoaPods'

  - script: |
      brew install gettext
    displayName: 'Install Gettext'

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'MacInstaller20210729.p12'
      certPwd: $(MAC_INSTALLER_P12_PASSWORD)
    displayName: 'Install Mac Installer Certificate'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'appStore' ))

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '20210508.p12'
      certPwd: $(P12Password)
    displayName: 'Install Distribution Certificate'
    condition: eq( variables['signing'], 'appStore' )

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'DeveloperID.p12'
      certPwd: $(P12Password)
    displayName: 'Install Developer ID Certificate'
    condition: and(eq( variables['sdk'], 'iphoneos' ), eq( variables['signing'], 'developerID' ))

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: MobileCelestiaDistrition20210508.mobileprovision
    displayName: 'Install Provision File (iOS)'
    condition: eq( variables['sdk'], 'iphoneos' )

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: MobileCelestiaDeveloperID20250605.provisionprofile
    displayName: 'Install Provision File (Catalyst, Developer ID)'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'developerID' ))

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: Ado_Mobile_Celestia_Catalyst_20211009.provisionprofile
    displayName: 'Install Provision File (Catalyst, App Store)'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'appStore' ))

  - task: Xcode@5
    inputs:
      actions: 'build'
      packageApp: true
      signingOption: manual
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
      scheme: 'MobileCelestia'
      sdk: $(sdk)
      configuration: 'Release'
      xcWorkspacePath: '$(system.defaultworkingdirectory)/MobileCelestia/MobileCelestia.xcworkspace'
      xcodeVersion: '13'
      exportPath: '$(agent.buildDirectory)/output/$(sdk)'
      archivePath: '$(system.defaultworkingdirectory)/archive'
    displayName: 'Build'

  - script: |
      cd $(system.defaultworkingdirectory)/archive
      zip -r -v -y $(Build.ArtifactStagingDirectory)/Archive.zip *.xcarchive
    displayName: 'Create .zip for .xcarchive'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(agent.buildDirectory)/output/$(sdk)'
      contents: '**/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
    displayName: 'Copy .ipa'
    condition: eq( variables['sdk'], 'iphoneos' )

  - script: |
      cd $(agent.buildDirectory)/output/$(sdk)
      zip -r -v -y $(Build.ArtifactStagingDirectory)/App.zip *.app
    displayName: 'Create .zip Archive for .app'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'developerID' ))

  - script: |
      cp -r $(agent.buildDirectory)/output/$(sdk)/**/*.pkg $(Build.ArtifactStagingDirectory)
    displayName: 'Copy .pkg'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'appStore' ))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(sdk)-$(signing)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia'
      appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
      symbolsDsymFiles: '$(system.defaultworkingdirectory)/archive/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center (iOS)'
    condition: eq( variables['sdk'], 'iphoneos' )

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCatalystCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia-3'
      appFile: '$(Build.ArtifactStagingDirectory)/App.zip'
      symbolsDsymFiles: '$(system.defaultworkingdirectory)/archive/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center (Developer ID)'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'developerID' ))

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCatalystCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia-3'
      appFile: '$(build.artifactstagingdirectory)/**/*.pkg'
      symbolsDsymFiles: '$(system.defaultworkingdirectory)/archive/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center (App Store)'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'appStore' ))

  - script: |
      xcrun altool --notarize-app --primary-bundle-id space.celestia.MobileCelestia --username $(AC_ACCOUNT_NAME) --password $(AC_ACCOUNT_PASSWORD) -f $(Build.ArtifactStagingDirectory)/App.zip
    displayName: "Notarize App"
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['siging'], 'developerID' ))
