jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'macos-latest'

  variables:
    sdk: ${{ parameters.sdk }}

  steps:
  - checkout: Celestia
    submodules: true
  - checkout: CelestiaCore
    submodules: true
  - checkout: self

  - script: |
      cd Celestia
      git cherry-pick origin/angle
    displayName: 'Cherry-Pick ANGLE Commit'
    condition: eq( variables['sdk'], 'macosx' )

  - script: |
      brew install gettext
    displayName: 'Install Gettext'

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: '20210508.p12'
      certPwd: $(P12Password)
    displayName: 'Install Certificate'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: MobileCelestiaDistrition20210508.mobileprovision
    displayName: 'Install Provision File'
    condition: ne( variables['sdk'], 'macosx' )

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provProfileSecureFile: MobileCelestiaCatalystDistrition20210508.provisionprofile
    displayName: 'Install Provision File'
    condition: eq( variables['sdk'], 'macosx' )

  - task: ios-bundle-version@1
    inputs:
      sourcePath: '$(system.defaultworkingdirectory)/MobileCelestia/MobileCelestia/Info.plist'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildId)'
      versionCodeOffset: '53'
      versionName:
      printFile: true
    displayName: 'Update Bundle Version'

  - task: Xcode@5
    inputs:
      actions: 'build'
      packageApp: true
      signingOption: manual
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
      scheme: 'MobileCelestia'
      sdk: $(sdk)
      configuration: 'Release'
      xcWorkspacePath: '$(system.defaultworkingdirectory)/MobileCelestia/MobileCelestia.xcodeproj/project.xcworkspace'
      xcodeVersion: 'default'
      exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      archivePath: '$(system.defaultworkingdirectory)/archive'
    displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      contents: '**/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
    displayName: 'Copy .ipa'
    condition: ne( variables['sdk'], 'macosx' )

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      contents: '**/*.pkg'
      targetFolder: '$(build.artifactStagingDirectory)'
    displayName: 'Copy .pkg'
    condition: eq( variables['sdk'], 'macosx' )

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(system.defaultworkingdirectory)/archive"
      contents: '**/*.dSYM/**'
      targetFolder: '$(build.artifactStagingDirectory)'
    displayName: 'Copy .dsym'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(sdk)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia'
      appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
      symbolsDsymFiles: '$(build.artifactstagingdirectory)/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center'
    condition: ne( variables['sdk'], 'macosx' )

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCatalystCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia-3'
      appFile: '$(build.artifactstagingdirectory)/**/*.pkg'
      symbolsDsymFiles: '$(build.artifactstagingdirectory)/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center'
    condition: eq( variables['sdk'], 'macosx' )
