jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'macos-11'

  variables:
    sdk: ${{ parameters.sdk }}
    signing: ${{ parameters.signing }}
    XC_VERSION: ${{ '13.0' }}
    XC_WORKSPACE: ${{ 'MobileCelestia/MobileCelestia.xcworkspace' }}
    XC_SCHEME: ${{ 'MobileCelestia' }}
    XC_ARCHIVE_PATH: ${{ './MobileCelestia.xcarchive' }}
    XC_EXPORT_OPTIONS_FILE_PATH: ${{ './ExportOptions.plist' }}
    XC_EXPORT_PATH: ${{ './artifacts/' }}

  steps:
  - checkout: Celestia
  - checkout: CelestiaCore
  - checkout: self

  - script: |
      cd Celestia
      git checkout origin/$(Build.SourceBranchName)
      git submodule update --init
      cd ../CelestiaCore
      git checkout origin/$(Build.SourceBranchName)
      git submodule update --init
    displayName: 'Checkout Branch'
    condition: ne( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd Celestia
      git checkout origin/$(System.PullRequest.TargetBranch)
      git submodule update --init
      cd ../CelestiaCore
      git checkout origin/$(System.PullRequest.TargetBranch)
      git submodule update --init
    displayName: 'Checkout Branch (PR)'
    condition: eq( variables['Build.Reason'], 'PullRequest' )

  - script: |
      cd Celestia
      git cherry-pick origin/angle
    displayName: 'Cherry-Pick ANGLE Commit'
    condition: eq( variables['sdk'], 'macosx' )

  - script: |
      sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app
    displayName: 'Select Latest Xcode'

  - script: |
      cd MobileCelestia
      pod deintegrate
      pod install
    displayName: 'Reintegrate CocoaPods'

  - script: |
      brew install gettext
    displayName: 'Install Gettext'

  - task: DownloadSecureFile@1
    name: macInstallerP12
    inputs:
      secureFile: 'MacInstaller20210729.p12'
    displayName: 'Download Mac Installer Certificate'

  - task: DownloadSecureFile@1
    name: distributionP12
    inputs:
      secureFile: '20210508.p12'
    displayName: 'Download Distribution Certificate'

  - task: DownloadSecureFile@1
    name: developerIDP12
    inputs:
      secureFile: 'DeveloperID.p12'
    displayName: 'Download Developer ID Certificate'

  - task: DownloadSecureFile@1
    name: iosProvisioningProfile
    inputs:
      secureFile: 'MobileCelestiaDistrition20210508.mobileprovision'
    displayName: 'Download iOS Provisioning Profile'

  - task: DownloadSecureFile@1
    name: macAppStoreProvisioningProfile
    inputs:
      secureFile: 'Ado_Mobile_Celestia_Catalyst_20211009.provisionprofile'
    displayName: 'Download Mac (App Store) Provisioning Profile'

  - task: DownloadSecureFile@1
    name: macDeveloperIDProvisioningProfile
    inputs:
      secureFile: 'MobileCelestiaDeveloperID20250605.provisionprofile'
    displayName: 'Download Mac (Developer ID) Provisioning Profile'

  - script: |
      # create variables
      KEYCHAIN_PATH=$(Agent.TempDirectory)/app-signing.keychain-db
      KEYCHAIN_PASSWORD=temppassword
      # create temporary keychain
      security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
      security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      # import certificate to keychain
      security import "$(macInstallerP12.secureFilePath)" -P "$(MAC_INSTALLER_P12_PASSWORD)" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
      security import "$(distributionP12.secureFilePath)" -P "$(P12Password" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
      security import "$(developerIDP12.secureFilePath)" -P "$(P12Password)" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
      security list-keychain -d user -s $KEYCHAIN_PATH
      # apply provisioning profile
      mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      echo "$(iosProvisioningProfile.secureFilePath)"
      cp "$(iosProvisioningProfile.secureFilePath)" ~/Library/MobileDevice/Provisioning\ Profiles
      cp "$(macAppStoreProvisioningProfile.secureFilePath)" ~/Library/MobileDevice/Provisioning\ Profiles
      cp "$(macDeveloperIDProvisioningProfile.secureFilePath)" ~/Library/MobileDevice/Provisioning\ Profiles
    displayName: 'Install Certificates and Provisioning Profiles'

  - script: |
      /usr/bin/xcodebuild archive -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -configuration "Release" -destination "generic/platform=iOS" -archivePath "$XC_ARCHIVE_PATH" CODE_SIGN_STYLE="Manual" PROVISIONING_PROFILE="AppCenterMC20210529" CODE_SIGN_IDENTITY="Apple Distribution: Linfeng Li (22NR5428TD)"
    displayName: 'Build Archive'

  - script: |
      /usr/bin/xcodebuild -exportArchive -archivePath "$XC_ARCHIVE_PATH" -exportOptionsPlist "$XC_EXPORT_OPTIONS_FILE_PATH" -exportPath "$XC_EXPORT_PATH"
    displayName: 'Export Archive'

  - script: |
      cd $(system.defaultworkingdirectory)/archive
      zip -r -v -y $(Build.ArtifactStagingDirectory)/Archive.zip *.xcarchive
    displayName: 'Create .zip for .xcarchive'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(agent.buildDirectory)/output/$(sdk)'
      contents: '**/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
    displayName: 'Copy .ipa'
    condition: eq( variables['sdk'], 'iphoneos' )

  - script: |
      cd $(agent.buildDirectory)/output/$(sdk)
      zip -r -v -y $(Build.ArtifactStagingDirectory)/App.zip *.app
    displayName: 'Create .zip Archive for .app'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'developerID' ))

  - script: |
      cp -r $(agent.buildDirectory)/output/$(sdk)/**/*.pkg $(Build.ArtifactStagingDirectory)
    displayName: 'Copy .pkg'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'appStore' ))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(sdk)-$(signing)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia'
      appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
      symbolsDsymFiles: '$(system.defaultworkingdirectory)/archive/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center (iOS)'
    condition: eq( variables['sdk'], 'iphoneos' )

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCatalystCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia-3'
      appFile: '$(Build.ArtifactStagingDirectory)/App.zip'
      symbolsDsymFiles: '$(system.defaultworkingdirectory)/archive/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center (Developer ID)'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'developerID' ))

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: MobileCatalystCelestiaAppCenter
      appSlug: 'CelestiaProject/Celestia-3'
      appFile: '$(build.artifactstagingdirectory)/**/*.pkg'
      symbolsDsymFiles: '$(system.defaultworkingdirectory)/archive/**/*.dSYM'
      releaseNotesOption: 'input'
      releaseNotesInput: 'Internal testing only.'
      destinationType: 'groups'
    displayName: 'Publish to App Center (App Store)'
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['signing'], 'appStore' ))

  - script: |
      xcrun altool --notarize-app --primary-bundle-id space.celestia.MobileCelestia --username $(AC_ACCOUNT_NAME) --password $(AC_ACCOUNT_PASSWORD) -f $(Build.ArtifactStagingDirectory)/App.zip
    displayName: "Notarize App"
    condition: and(eq( variables['sdk'], 'macosx' ), eq( variables['siging'], 'developerID' ))
